ACCOUNT_BALANCE = 22000
MAX_NOTIONAL_LIMIT = 0.25  # BTC
TARGET_DELTA = (0.15, 0.20)
MIN_DVOL_PULSE = 0.10  # 10%
LOOKBACK_PERIOD = 365  # days

DERIBIT_BASE_URL = "https://www.deribit.com/api/v2"
BTC_INDEX_NAME = "btc_usd"
DVOL_SYMBOL = "DVOL"
